# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from pfruck_contabo.models.remedy_template_summary import RemedyTemplateSummary
from typing import Optional, Set
from typing_extensions import Self

class CheckCollectionTemplatesCheckTemplates(BaseModel):
    """
    CheckCollectionTemplatesCheckTemplates
    """ # noqa: E501
    check_template_id: Union[StrictFloat, StrictInt] = Field(description="Id of the check template", alias="checkTemplateId")
    run_concurrent: StrictBool = Field(description="Can this check template be run in parallel with other checks", alias="runConcurrent")
    ignore_errors: StrictBool = Field(description="Will errors be ignored when running this check template", alias="ignoreErrors")
    remedy_templates: Optional[List[RemedyTemplateSummary]] = Field(default=None, description="Remedy templates linked to this check template", alias="remedyTemplates")
    check_templates: Optional[List[CheckCollectionTemplatesCheckTemplates]] = Field(default=None, description="Nested check templates", alias="checkTemplates")
    __properties: ClassVar[List[str]] = ["checkTemplateId", "runConcurrent", "ignoreErrors", "remedyTemplates", "checkTemplates"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckCollectionTemplatesCheckTemplates from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in remedy_templates (list)
        _items = []
        if self.remedy_templates:
            for _item in self.remedy_templates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['remedyTemplates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in check_templates (list)
        _items = []
        if self.check_templates:
            for _item in self.check_templates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['checkTemplates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckCollectionTemplatesCheckTemplates from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "checkTemplateId": obj.get("checkTemplateId"),
            "runConcurrent": obj.get("runConcurrent"),
            "ignoreErrors": obj.get("ignoreErrors"),
            "remedyTemplates": [RemedyTemplateSummary.from_dict(_item) for _item in obj["remedyTemplates"]] if obj.get("remedyTemplates") is not None else None,
            "checkTemplates": [CheckCollectionTemplatesCheckTemplates.from_dict(_item) for _item in obj["checkTemplates"]] if obj.get("checkTemplates") is not None else None
        })
        return _obj

# TODO: Rewrite to not use raise_errors
CheckCollectionTemplatesCheckTemplates.model_rebuild(raise_errors=False)

