# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from pfruck_contabo.models.check_collection_check_templates import CheckCollectionCheckTemplates
from pfruck_contabo.models.check_response import CheckResponse
from typing import Optional, Set
from typing_extensions import Self

class CheckCollectionResponse(BaseModel):
    """
    CheckCollectionResponse
    """ # noqa: E501
    internal: StrictBool = Field(description="Is internal (not shown to the customer)")
    status: StrictStr = Field(description="Status of the handle")
    object_type: StrictStr = Field(description="Object type to be handled", alias="objectType")
    object_id: StrictStr = Field(description="ID of the object, to be handled", alias="objectId")
    check_collection_id: Union[StrictFloat, StrictInt] = Field(description="Check collection's id", alias="checkCollectionId")
    check_collection_template_id: Union[StrictFloat, StrictInt] = Field(description="Check Collection Template for this check collection", alias="checkCollectionTemplateId")
    check_templates: List[CheckCollectionCheckTemplates] = Field(description="Check templates which are part of this collection template", alias="checkTemplates")
    created_date: datetime = Field(description="Creation date", alias="createdDate")
    modified_date: datetime = Field(description="Modify date", alias="modifiedDate")
    org_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Org id", alias="orgId")
    account_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Account id", alias="accountId")
    checks: List[CheckResponse] = Field(description="Checks performed in this check collection")
    __properties: ClassVar[List[str]] = ["internal", "status", "objectType", "objectId", "checkCollectionId", "checkCollectionTemplateId", "checkTemplates", "createdDate", "modifiedDate", "orgId", "accountId", "checks"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['queued', 'running', 'skipped', 'cancelled', 'failed', 'warn', 'successful']):
            raise ValueError("must be one of enum values ('queued', 'running', 'skipped', 'cancelled', 'failed', 'warn', 'successful')")
        return value

    @field_validator('object_type')
    def object_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['vserver']):
            raise ValueError("must be one of enum values ('vserver')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckCollectionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in check_templates (list)
        _items = []
        if self.check_templates:
            for _item in self.check_templates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['checkTemplates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in checks (list)
        _items = []
        if self.checks:
            for _item in self.checks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['checks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckCollectionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "internal": obj.get("internal"),
            "status": obj.get("status"),
            "objectType": obj.get("objectType"),
            "objectId": obj.get("objectId"),
            "checkCollectionId": obj.get("checkCollectionId"),
            "checkCollectionTemplateId": obj.get("checkCollectionTemplateId"),
            "checkTemplates": [CheckCollectionCheckTemplates.from_dict(_item) for _item in obj["checkTemplates"]] if obj.get("checkTemplates") is not None else None,
            "createdDate": obj.get("createdDate"),
            "modifiedDate": obj.get("modifiedDate"),
            "orgId": obj.get("orgId"),
            "accountId": obj.get("accountId"),
            "checks": [CheckResponse.from_dict(_item) for _item in obj["checks"]] if obj.get("checks") is not None else None
        })
        return _obj


