# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pfruck_contabo.models.src_cidr import SrcCidr
from typing import Optional, Set
from typing_extensions import Self

class FirewallRuleRequest(BaseModel):
    """
    FirewallRuleRequest
    """ # noqa: E501
    protocol: StrictStr = Field(description="Protocol for incoming traffic to be allowed. ‘tcp‘, ´udp´, ´icmp´ or ´´ empty value are allowed. Empty means any traffic.")
    dest_ports: List[Annotated[str, Field(strict=True)]] = Field(description="Ports to specify allowed traffic. Not available for protocol `ICMP`. Port ranges can specified like in example.", alias="destPorts")
    src_cidr: SrcCidr = Field(description="Source CIDR configuration. Use \"AnyIPv4\" to allow all IPv4 sources (0.0.0.0/0) or \"AnyIPv6\" to allow all IPv6 sources (::/0). Both can be combined to allow all IP sources. Regular CIDR notation is also supported.", alias="srcCidr")
    action: StrictStr = Field(description="Currently only `accept` is supported.")
    status: StrictStr = Field(description="Status of the inbound rule. An inactive rule is removed from all assigned instances.")
    display_name: Optional[StrictStr] = Field(default=None, description="Display name for the firewall rule.", alias="displayName")
    __properties: ClassVar[List[str]] = ["protocol", "destPorts", "srcCidr", "action", "status", "displayName"]

    @field_validator('protocol')
    def protocol_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['tcp', 'udp', 'icmp', '']):
            raise ValueError("must be one of enum values ('tcp', 'udp', 'icmp', '')")
        return value

    @field_validator('action')
    def action_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['accept', 'drop']):
            raise ValueError("must be one of enum values ('accept', 'drop')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'inactive']):
            raise ValueError("must be one of enum values ('active', 'inactive')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FirewallRuleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of src_cidr
        if self.src_cidr:
            _dict['srcCidr'] = self.src_cidr.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FirewallRuleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "protocol": obj.get("protocol"),
            "destPorts": obj.get("destPorts"),
            "srcCidr": SrcCidr.from_dict(obj["srcCidr"]) if obj.get("srcCidr") is not None else None,
            "action": obj.get("action"),
            "status": obj.get("status"),
            "displayName": obj.get("displayName")
        })
        return _obj


