# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PermissionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api_name': 'str',
        'actions': 'list[str]',
        'resources': 'list[int]'
    }

    attribute_map = {
        'api_name': 'apiName',
        'actions': 'actions',
        'resources': 'resources'
    }

    def __init__(self, api_name=None, actions=None, resources=None):  # noqa: E501
        """PermissionRequest - a model defined in Swagger"""  # noqa: E501
        self._api_name = None
        self._actions = None
        self._resources = None
        self.discriminator = None
        self.api_name = api_name
        self.actions = actions
        if resources is not None:
            self.resources = resources

    @property
    def api_name(self):
        """Gets the api_name of this PermissionRequest.  # noqa: E501

        The name of the role. There is a limit of 255 characters per role.  # noqa: E501

        :return: The api_name of this PermissionRequest.  # noqa: E501
        :rtype: str
        """
        return self._api_name

    @api_name.setter
    def api_name(self, api_name):
        """Sets the api_name of this PermissionRequest.

        The name of the role. There is a limit of 255 characters per role.  # noqa: E501

        :param api_name: The api_name of this PermissionRequest.  # noqa: E501
        :type: str
        """
        if api_name is None:
            raise ValueError("Invalid value for `api_name`, must not be `None`")  # noqa: E501

        self._api_name = api_name

    @property
    def actions(self):
        """Gets the actions of this PermissionRequest.  # noqa: E501

        Action allowed for the API endpoint. Basically `CREATE` corresponds to POST endpoints, `READ` to GET endpoints, `UPDATE` to PATCH / PUT endpoints and `DELETE` to DELETE endpoints.  # noqa: E501

        :return: The actions of this PermissionRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """Sets the actions of this PermissionRequest.

        Action allowed for the API endpoint. Basically `CREATE` corresponds to POST endpoints, `READ` to GET endpoints, `UPDATE` to PATCH / PUT endpoints and `DELETE` to DELETE endpoints.  # noqa: E501

        :param actions: The actions of this PermissionRequest.  # noqa: E501
        :type: list[str]
        """
        if actions is None:
            raise ValueError("Invalid value for `actions`, must not be `None`")  # noqa: E501
        allowed_values = ["CREATE", "READ", "UPDATE", "DELETE"]  # noqa: E501
        if not set(actions).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `actions` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(actions) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._actions = actions

    @property
    def resources(self):
        """Gets the resources of this PermissionRequest.  # noqa: E501

        The IDs of tags. Only if those tags are assgined to a resource the user with that role will be able to access the resource.  # noqa: E501

        :return: The resources of this PermissionRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this PermissionRequest.

        The IDs of tags. Only if those tags are assgined to a resource the user with that role will be able to access the resource.  # noqa: E501

        :param resources: The resources of this PermissionRequest.  # noqa: E501
        :type: list[int]
        """

        self._resources = resources

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PermissionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PermissionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
