# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RemedyResponse(BaseModel):
    """
    RemedyResponse
    """ # noqa: E501
    internal: StrictBool = Field(description="Is internal (not shown to the customer)")
    status: StrictStr = Field(description="Status of the handle")
    object_type: StrictStr = Field(description="Object type to be handled", alias="objectType")
    object_id: StrictStr = Field(description="ID of the object, to be handled", alias="objectId")
    remedy_id: Union[StrictFloat, StrictInt] = Field(description="Remedy's id", alias="remedyId")
    remedy_collection_id: Union[StrictFloat, StrictInt] = Field(description="ID of remedy collection if started in scope of a collection", alias="remedyCollectionId")
    remedy_template_id: Union[StrictFloat, StrictInt] = Field(description="Remedy Template for this remedy", alias="remedyTemplateId")
    name: StrictStr = Field(description="Name of this remedy template")
    note: StrictStr = Field(description="Translation key for the customer-facing remedy note. Possible values: fail_remedy_failed, success_remedy_successful, remedy_internal_error, instance_firewall_detach_successful, instance_live_migration_successful, instance_reboot_successful")
    internal_note: StrictStr = Field(description="Translation key for the internal-only remedy note (agent view). Possible values: remedy_internal_error_internal, instance_firewall_detach_successful_internal, instance_live_migration_successful_internal, instance_reboot_successful_internal", alias="internalNote")
    duration_ms: Union[StrictFloat, StrictInt] = Field(description="Duration of the remedy in milliseconds", alias="durationMs")
    created_date: datetime = Field(description="Creation date", alias="createdDate")
    modified_date: datetime = Field(description="Modify date", alias="modifiedDate")
    org_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Org id", alias="orgId")
    account_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Account id", alias="accountId")
    log: StrictStr = Field(description="Detailed log of the check execution")
    __properties: ClassVar[List[str]] = ["internal", "status", "objectType", "objectId", "remedyId", "remedyCollectionId", "remedyTemplateId", "name", "note", "internalNote", "durationMs", "createdDate", "modifiedDate", "orgId", "accountId", "log"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['queued', 'running', 'skipped', 'cancelled', 'failed', 'warn', 'successful']):
            raise ValueError("must be one of enum values ('queued', 'running', 'skipped', 'cancelled', 'failed', 'warn', 'successful')")
        return value

    @field_validator('object_type')
    def object_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['vserver']):
            raise ValueError("must be one of enum values ('vserver')")
        return value

    @field_validator('note')
    def note_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['fail_remedy_failed', 'success_remedy_successful', 'remedy_internal_error', 'instance_firewall_detach_successful', 'instance_live_migration_successful', 'instance_reboot_successful']):
            raise ValueError("must be one of enum values ('fail_remedy_failed', 'success_remedy_successful', 'remedy_internal_error', 'instance_firewall_detach_successful', 'instance_live_migration_successful', 'instance_reboot_successful')")
        return value

    @field_validator('internal_note')
    def internal_note_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['remedy_internal_error_internal', 'instance_firewall_detach_successful_internal', 'instance_live_migration_successful_internal', 'instance_reboot_successful_internal']):
            raise ValueError("must be one of enum values ('remedy_internal_error_internal', 'instance_firewall_detach_successful_internal', 'instance_live_migration_successful_internal', 'instance_reboot_successful_internal')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RemedyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RemedyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "internal": obj.get("internal"),
            "status": obj.get("status"),
            "objectType": obj.get("objectType"),
            "objectId": obj.get("objectId"),
            "remedyId": obj.get("remedyId"),
            "remedyCollectionId": obj.get("remedyCollectionId"),
            "remedyTemplateId": obj.get("remedyTemplateId"),
            "name": obj.get("name"),
            "note": obj.get("note"),
            "internalNote": obj.get("internalNote"),
            "durationMs": obj.get("durationMs"),
            "createdDate": obj.get("createdDate"),
            "modifiedDate": obj.get("modifiedDate"),
            "orgId": obj.get("orgId"),
            "accountId": obj.get("accountId"),
            "log": obj.get("log")
        })
        return _obj


