"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import pfruck_contabo
from pfruck_contabo.api.users_audits_api import UsersAuditsApi  # noqa: E501


class TestUsersAuditsApi(unittest.TestCase):
    """UsersAuditsApi unit test stubs"""

    def setUp(self):
        self.api = UsersAuditsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_user_audits_list(self):
        """Test case for retrieve_user_audits_list

        List history about your users (audit)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
