"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.subscription_pricing import SubscriptionPricing


class TestSubscriptionPricing(unittest.TestCase):
    """SubscriptionPricing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionPricing(self):
        """Test SubscriptionPricing"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubscriptionPricing()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
