# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.api.private_networks_api import PrivateNetworksApi


class TestPrivateNetworksApi(unittest.TestCase):
    """PrivateNetworksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PrivateNetworksApi()

    def tearDown(self) -> None:
        pass

    def test_assign_instance_private_network(self) -> None:
        """Test case for assign_instance_private_network

        Add instance to a Private Network
        """
        pass

    def test_create_private_network(self) -> None:
        """Test case for create_private_network

        Create a new Private Network
        """
        pass

    def test_delete_private_network(self) -> None:
        """Test case for delete_private_network

        Delete existing Private Network by id
        """
        pass

    def test_patch_private_network(self) -> None:
        """Test case for patch_private_network

        Update a Private Network by id
        """
        pass

    def test_retrieve_private_network(self) -> None:
        """Test case for retrieve_private_network

        Get specific Private Network by id
        """
        pass

    def test_retrieve_private_network_list(self) -> None:
        """Test case for retrieve_private_network_list

        List Private Networks
        """
        pass

    def test_unassign_instance_private_network(self) -> None:
        """Test case for unassign_instance_private_network

        Remove instance from a Private Network
        """
        pass


if __name__ == '__main__':
    unittest.main()
