# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.models.user_is_password_set_response import UserIsPasswordSetResponse  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestUserIsPasswordSetResponse(unittest.TestCase):
    """UserIsPasswordSetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserIsPasswordSetResponse(self):
        """Test UserIsPasswordSetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pfruck_contabo.models.user_is_password_set_response.UserIsPasswordSetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
