# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.check_templates_list_response import CheckTemplatesListResponse

class TestCheckTemplatesListResponse(unittest.TestCase):
    """CheckTemplatesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckTemplatesListResponse:
        """Test CheckTemplatesListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckTemplatesListResponse`
        """
        model = CheckTemplatesListResponse()
        if include_optional:
            return CheckTemplatesListResponse(
                pagination = pfruck_contabo.models.pagination_meta.PaginationMeta(
                    size = 10, 
                    total_elements = 100, 
                    total_pages = 10, 
                    page = 1, ),
                data = [
                    pfruck_contabo.models.check_template_response.CheckTemplateResponse(
                        created_date = '1998-02-14T12:00:01.654Z', 
                        modified_date = '2024-12-14T12:00:01.654Z', 
                        org_id = 'cntb', 
                        account_id = 'd8d15718-8f0a-4933-8844-6b69b9c2f15f', 
                        check_template_id = 12345, 
                        name = 'Ping check instance', 
                        description = 'Performs a ping check on an instance', 
                        internal = False, 
                        object_type = 'vserver', 
                        collector_class = 'InstanceCollector.ts', 
                        check_class = 'PingCheck.ts', 
                        remedy_template_ids = 1, 2, ..., )
                    ],
                links = pfruck_contabo.models.links.Links(
                    self = '', 
                    first = '', 
                    previous = '', 
                    next = '', 
                    last = '', )
            )
        else:
            return CheckTemplatesListResponse(
                pagination = pfruck_contabo.models.pagination_meta.PaginationMeta(
                    size = 10, 
                    total_elements = 100, 
                    total_pages = 10, 
                    page = 1, ),
                data = [
                    pfruck_contabo.models.check_template_response.CheckTemplateResponse(
                        created_date = '1998-02-14T12:00:01.654Z', 
                        modified_date = '2024-12-14T12:00:01.654Z', 
                        org_id = 'cntb', 
                        account_id = 'd8d15718-8f0a-4933-8844-6b69b9c2f15f', 
                        check_template_id = 12345, 
                        name = 'Ping check instance', 
                        description = 'Performs a ping check on an instance', 
                        internal = False, 
                        object_type = 'vserver', 
                        collector_class = 'InstanceCollector.ts', 
                        check_class = 'PingCheck.ts', 
                        remedy_template_ids = 1, 2, ..., )
                    ],
                links = pfruck_contabo.models.links.Links(
                    self = '', 
                    first = '', 
                    previous = '', 
                    next = '', 
                    last = '', ),
        )
        """

    def testCheckTemplatesListResponse(self):
        """Test CheckTemplatesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
