"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.instance_restart_action_response_data import InstanceRestartActionResponseData
from pfruck_contabo.model.instance_restart_action_response_links import InstanceRestartActionResponseLinks
globals()['InstanceRestartActionResponseData'] = InstanceRestartActionResponseData
globals()['InstanceRestartActionResponseLinks'] = InstanceRestartActionResponseLinks
from pfruck_contabo.model.instance_restart_action_response import InstanceRestartActionResponse


class TestInstanceRestartActionResponse(unittest.TestCase):
    """InstanceRestartActionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceRestartActionResponse(self):
        """Test InstanceRestartActionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstanceRestartActionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
