# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.instance_reset_password_action_response import InstanceResetPasswordActionResponse

class TestInstanceResetPasswordActionResponse(unittest.TestCase):
    """InstanceResetPasswordActionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceResetPasswordActionResponse:
        """Test InstanceResetPasswordActionResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceResetPasswordActionResponse`
        """
        model = InstanceResetPasswordActionResponse()
        if include_optional:
            return InstanceResetPasswordActionResponse(
                data = [
                    pfruck_contabo.models.instance_reset_password_action_response_data.InstanceResetPasswordActionResponseData(
                        tenant_id = 'DE', 
                        customer_id = '54321', 
                        instance_id = 12345, 
                        action = 'start', )
                    ],
                links = pfruck_contabo.models.self_links.SelfLinks(
                    self = '', )
            )
        else:
            return InstanceResetPasswordActionResponse(
                data = [
                    pfruck_contabo.models.instance_reset_password_action_response_data.InstanceResetPasswordActionResponseData(
                        tenant_id = 'DE', 
                        customer_id = '54321', 
                        instance_id = 12345, 
                        action = 'start', )
                    ],
                links = pfruck_contabo.models.self_links.SelfLinks(
                    self = '', ),
        )
        """

    def testInstanceResetPasswordActionResponse(self):
        """Test InstanceResetPasswordActionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
