"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.self_links import SelfLinks
from pfruck_contabo.model.update_object_storage_response_data import UpdateObjectStorageResponseData
globals()['SelfLinks'] = SelfLinks
globals()['UpdateObjectStorageResponseData'] = UpdateObjectStorageResponseData
from pfruck_contabo.model.update_object_storage_response import UpdateObjectStorageResponse


class TestUpdateObjectStorageResponse(unittest.TestCase):
    """UpdateObjectStorageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateObjectStorageResponse(self):
        """Test UpdateObjectStorageResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateObjectStorageResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
