# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.vip_audit_response import VipAuditResponse

class TestVipAuditResponse(unittest.TestCase):
    """VipAuditResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VipAuditResponse:
        """Test VipAuditResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VipAuditResponse`
        """
        model = VipAuditResponse()
        if include_optional:
            return VipAuditResponse(
                id = 12345,
                vip_id = 'b943b25a-c8b5-4570-9135-4bbaa7615b81',
                action = 'CREATED',
                timestamp = '2021-03-30T11:35:06.177Z',
                tenant_id = 'DE',
                customer_id = '54321',
                changed_by = '54321',
                username = 'John Doe',
                request_id = 'A2F56FAF-18N0-4893-11HG-R312M1E4FEC5',
                trace_id = '78E9A428-94E9-4A2A-92F5-26038C6884F',
                changes = {"prev":{"name":"test"},"new":{"name":"test1"}}
            )
        else:
            return VipAuditResponse(
                id = 12345,
                vip_id = 'b943b25a-c8b5-4570-9135-4bbaa7615b81',
                action = 'CREATED',
                timestamp = '2021-03-30T11:35:06.177Z',
                tenant_id = 'DE',
                customer_id = '54321',
                changed_by = '54321',
                username = 'John Doe',
                request_id = 'A2F56FAF-18N0-4893-11HG-R312M1E4FEC5',
                trace_id = '78E9A428-94E9-4A2A-92F5-26038C6884F',
        )
        """

    def testVipAuditResponse(self):
        """Test VipAuditResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
