# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.api.roles_audits_api import RolesAuditsApi  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestRolesAuditsApi(unittest.TestCase):
    """RolesAuditsApi unit test stubs"""

    def setUp(self):
        self.api = RolesAuditsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_role_audits_list(self):
        """Test case for retrieve_role_audits_list

        List history about your roles (audit)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
