# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.user_is_password_set_response import UserIsPasswordSetResponse

class TestUserIsPasswordSetResponse(unittest.TestCase):
    """UserIsPasswordSetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserIsPasswordSetResponse:
        """Test UserIsPasswordSetResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserIsPasswordSetResponse`
        """
        model = UserIsPasswordSetResponse()
        if include_optional:
            return UserIsPasswordSetResponse(
                tenant_id = 'DE',
                customer_id = '54321',
                is_password_set = False
            )
        else:
            return UserIsPasswordSetResponse(
                tenant_id = 'DE',
                customer_id = '54321',
                is_password_set = False,
        )
        """

    def testUserIsPasswordSetResponse(self):
        """Test UserIsPasswordSetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
