"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.instance_assignment_self_links import InstanceAssignmentSelfLinks


class TestInstanceAssignmentSelfLinks(unittest.TestCase):
    """InstanceAssignmentSelfLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceAssignmentSelfLinks(self):
        """Test InstanceAssignmentSelfLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstanceAssignmentSelfLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
