# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.api.user_accounts_api import UserAccountsApi


class TestUserAccountsApi(unittest.TestCase):
    """UserAccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserAccountsApi()

    def tearDown(self) -> None:
        pass

    def test_list_user_accounts(self) -> None:
        """Test case for list_user_accounts

        List of your accounts
        """
        pass

    def test_make_default_account(self) -> None:
        """Test case for make_default_account

        Make user account default
        """
        pass

    def test_switch_account(self) -> None:
        """Test case for switch_account

        Switch user account
        """
        pass


if __name__ == '__main__':
    unittest.main()
