"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.list_role_audit_response_links import ListRoleAuditResponseLinks
from pfruck_contabo.model.role_audit_response import RoleAuditResponse
globals()['ListRoleAuditResponseLinks'] = ListRoleAuditResponseLinks
globals()['RoleAuditResponse'] = RoleAuditResponse
from pfruck_contabo.model.list_role_audit_response import ListRoleAuditResponse


class TestListRoleAuditResponse(unittest.TestCase):
    """ListRoleAuditResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListRoleAuditResponse(self):
        """Test ListRoleAuditResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListRoleAuditResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
