# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.models.all_of_create_object_storage_response_data_auto_scaling import AllOfCreateObjectStorageResponseDataAutoScaling  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestAllOfCreateObjectStorageResponseDataAutoScaling(unittest.TestCase):
    """AllOfCreateObjectStorageResponseDataAutoScaling unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfCreateObjectStorageResponseDataAutoScaling(self):
        """Test AllOfCreateObjectStorageResponseDataAutoScaling"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pfruck_contabo.models.all_of_create_object_storage_response_data_auto_scaling.AllOfCreateObjectStorageResponseDataAutoScaling()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
