# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.models.all_of_list_secret_response_pagination import AllOfListSecretResponsePagination  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestAllOfListSecretResponsePagination(unittest.TestCase):
    """AllOfListSecretResponsePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfListSecretResponsePagination(self):
        """Test AllOfListSecretResponsePagination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pfruck_contabo.models.all_of_list_secret_response_pagination.AllOfListSecretResponsePagination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
