"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.find_firewall_response_links import FindFirewallResponseLinks
from pfruck_contabo.model.firewall_response import FirewallResponse
globals()['FindFirewallResponseLinks'] = FindFirewallResponseLinks
globals()['FirewallResponse'] = FirewallResponse
from pfruck_contabo.model.find_firewall_response import FindFirewallResponse


class TestFindFirewallResponse(unittest.TestCase):
    """FindFirewallResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFindFirewallResponse(self):
        """Test FindFirewallResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FindFirewallResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
