# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.api.handles_audits_api import HandlesAuditsApi


class TestHandlesAuditsApi(unittest.TestCase):
    """HandlesAuditsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HandlesAuditsApi()

    def tearDown(self) -> None:
        pass

    def test_retrieve_handles_audits_list(self) -> None:
        """Test case for retrieve_handles_audits_list

        List history about your handles (audit)
        """
        pass


if __name__ == '__main__':
    unittest.main()
