# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.models.credential_response import CredentialResponse  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestCredentialResponse(unittest.TestCase):
    """CredentialResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredentialResponse(self):
        """Test CredentialResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pfruck_contabo.models.credential_response.CredentialResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
