"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.resource_permissions_response import ResourcePermissionsResponse
globals()['ResourcePermissionsResponse'] = ResourcePermissionsResponse
from pfruck_contabo.model.permission_response import PermissionResponse


class TestPermissionResponse(unittest.TestCase):
    """PermissionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPermissionResponse(self):
        """Test PermissionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PermissionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
