# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.dns_zone_response import DnsZoneResponse

class TestDnsZoneResponse(unittest.TestCase):
    """DnsZoneResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DnsZoneResponse:
        """Test DnsZoneResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DnsZoneResponse`
        """
        model = DnsZoneResponse()
        if include_optional:
            return DnsZoneResponse(
                tenant_id = 'DE',
                customer_id = '3f184ab8-a600-4e7c-8c9b-3413e21a3752',
                zone_name = 'abcdefg'
            )
        else:
            return DnsZoneResponse(
                tenant_id = 'DE',
                customer_id = '3f184ab8-a600-4e7c-8c9b-3413e21a3752',
                zone_name = 'abcdefg',
        )
        """

    def testDnsZoneResponse(self):
        """Test DnsZoneResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
