"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.firewall_rule_response import FirewallRuleResponse
globals()['FirewallRuleResponse'] = FirewallRuleResponse
from pfruck_contabo.model.rules import Rules


class TestRules(unittest.TestCase):
    """Rules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRules(self):
        """Test Rules"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Rules()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
