"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.dpa_response_data import DpaResponseData
from pfruck_contabo.model.dpa_response_links import DpaResponseLinks
globals()['DpaResponseData'] = DpaResponseData
globals()['DpaResponseLinks'] = DpaResponseLinks
from pfruck_contabo.model.dpa_response import DpaResponse


class TestDpaResponse(unittest.TestCase):
    """DpaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDpaResponse(self):
        """Test DpaResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DpaResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
