"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.instance_details import InstanceDetails
from pfruck_contabo.model.instance_status_representation import InstanceStatusRepresentation
from pfruck_contabo.model.rules import Rules
globals()['InstanceDetails'] = InstanceDetails
globals()['InstanceStatusRepresentation'] = InstanceStatusRepresentation
globals()['Rules'] = Rules
from pfruck_contabo.model.firewall_response import FirewallResponse


class TestFirewallResponse(unittest.TestCase):
    """FirewallResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFirewallResponse(self):
        """Test FirewallResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FirewallResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
