"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.customer_email import CustomerEmail


class TestCustomerEmail(unittest.TestCase):
    """CustomerEmail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomerEmail(self):
        """Test CustomerEmail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomerEmail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
