# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.handle_list_response import HandleListResponse

class TestHandleListResponse(unittest.TestCase):
    """HandleListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandleListResponse:
        """Test HandleListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandleListResponse`
        """
        model = HandleListResponse()
        if include_optional:
            return HandleListResponse(
                pagination = pfruck_contabo.models.pagination_meta.PaginationMeta(
                    size = 10, 
                    total_elements = 100, 
                    total_pages = 10, 
                    page = 1, ),
                data = [
                    pfruck_contabo.models.handle_response.HandleResponse(
                        tenant_id = 'DE', 
                        customer_id = '3f184ab8-a600-4e7c-8c9b-3413e21a3752', 
                        handle_id = 'CA1234O1', 
                        handle_type = 'person', 
                        is_default = True, 
                        alias = 'billing-contact', 
                        first_name = 'John', 
                        last_name = 'Doe', 
                        organization = 'Test Organization', 
                        email = 'john.doe@test.com', 
                        gender = 'male', 
                        birth_info = null, 
                        address = null, 
                        phone = null, 
                        fax = null, 
                        nic_it_entity_type = 'natural_person', 
                        pin = 'MRORSS77T05E472I', 
                        legal_status = 'company', 
                        sidn_legal_form = 'BV', 
                        sidn_legal_form_reg_no = '12345678', )
                    ],
                links = pfruck_contabo.models.links.Links(
                    self = '', 
                    first = '', 
                    previous = '', 
                    next = '', 
                    last = '', )
            )
        else:
            return HandleListResponse(
                pagination = pfruck_contabo.models.pagination_meta.PaginationMeta(
                    size = 10, 
                    total_elements = 100, 
                    total_pages = 10, 
                    page = 1, ),
                data = [
                    pfruck_contabo.models.handle_response.HandleResponse(
                        tenant_id = 'DE', 
                        customer_id = '3f184ab8-a600-4e7c-8c9b-3413e21a3752', 
                        handle_id = 'CA1234O1', 
                        handle_type = 'person', 
                        is_default = True, 
                        alias = 'billing-contact', 
                        first_name = 'John', 
                        last_name = 'Doe', 
                        organization = 'Test Organization', 
                        email = 'john.doe@test.com', 
                        gender = 'male', 
                        birth_info = null, 
                        address = null, 
                        phone = null, 
                        fax = null, 
                        nic_it_entity_type = 'natural_person', 
                        pin = 'MRORSS77T05E472I', 
                        legal_status = 'company', 
                        sidn_legal_form = 'BV', 
                        sidn_legal_form_reg_no = '12345678', )
                    ],
                links = pfruck_contabo.models.links.Links(
                    self = '', 
                    first = '', 
                    previous = '', 
                    next = '', 
                    last = '', ),
        )
        """

    def testHandleListResponse(self):
        """Test HandleListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
