"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.self_links import SelfLinks
globals()['SelfLinks'] = SelfLinks
from pfruck_contabo.model.instance_start_action_response_links import InstanceStartActionResponseLinks


class TestInstanceStartActionResponseLinks(unittest.TestCase):
    """InstanceStartActionResponseLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceStartActionResponseLinks(self):
        """Test InstanceStartActionResponseLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstanceStartActionResponseLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
