# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.models.object_storages_stats_response_data import ObjectStoragesStatsResponseData  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestObjectStoragesStatsResponseData(unittest.TestCase):
    """ObjectStoragesStatsResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectStoragesStatsResponseData(self):
        """Test ObjectStoragesStatsResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pfruck_contabo.models.object_storages_stats_response_data.ObjectStoragesStatsResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
