"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.cancel_object_storage_response_data import CancelObjectStorageResponseData
from pfruck_contabo.model.self_links import SelfLinks
globals()['CancelObjectStorageResponseData'] = CancelObjectStorageResponseData
globals()['SelfLinks'] = SelfLinks
from pfruck_contabo.model.cancel_object_storage_response import CancelObjectStorageResponse


class TestCancelObjectStorageResponse(unittest.TestCase):
    """CancelObjectStorageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCancelObjectStorageResponse(self):
        """Test CancelObjectStorageResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CancelObjectStorageResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
