"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.create_private_network_response_links import CreatePrivateNetworkResponseLinks
from pfruck_contabo.model.private_network_response import PrivateNetworkResponse
globals()['CreatePrivateNetworkResponseLinks'] = CreatePrivateNetworkResponseLinks
globals()['PrivateNetworkResponse'] = PrivateNetworkResponse
from pfruck_contabo.model.patch_private_network_response import PatchPrivateNetworkResponse


class TestPatchPrivateNetworkResponse(unittest.TestCase):
    """PatchPrivateNetworkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchPrivateNetworkResponse(self):
        """Test PatchPrivateNetworkResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchPrivateNetworkResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
