"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.private_network_response import PrivateNetworkResponse
from pfruck_contabo.model.self_links import SelfLinks
globals()['PrivateNetworkResponse'] = PrivateNetworkResponse
globals()['SelfLinks'] = SelfLinks
from pfruck_contabo.model.find_private_network_response import FindPrivateNetworkResponse


class TestFindPrivateNetworkResponse(unittest.TestCase):
    """FindPrivateNetworkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFindPrivateNetworkResponse(self):
        """Test FindPrivateNetworkResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FindPrivateNetworkResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
