"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.ip_v41 import IpV41


class TestIpV41(unittest.TestCase):
    """IpV41 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIpV41(self):
        """Test IpV41"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IpV41()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
