# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.models.update_object_storage_response import UpdateObjectStorageResponse  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestUpdateObjectStorageResponse(unittest.TestCase):
    """UpdateObjectStorageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateObjectStorageResponse(self):
        """Test UpdateObjectStorageResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pfruck_contabo.models.update_object_storage_response.UpdateObjectStorageResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
