# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.models.all_of_find_secret_response_links import AllOfFindSecretResponseLinks  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestAllOfFindSecretResponseLinks(unittest.TestCase):
    """AllOfFindSecretResponseLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfFindSecretResponseLinks(self):
        """Test AllOfFindSecretResponseLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pfruck_contabo.models.all_of_find_secret_response_links.AllOfFindSecretResponseLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
