"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import pfruck_contabo
from pfruck_contabo.api.object_storages_audits_api import ObjectStoragesAuditsApi  # noqa: E501


class TestObjectStoragesAuditsApi(unittest.TestCase):
    """ObjectStoragesAuditsApi unit test stubs"""

    def setUp(self):
        self.api = ObjectStoragesAuditsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_object_storage_audits_list(self):
        """Test case for retrieve_object_storage_audits_list

        List history about your object storages (audit)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
