"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.add_on_request import AddOnRequest


class TestAddOnRequest(unittest.TestCase):
    """AddOnRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddOnRequest(self):
        """Test AddOnRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddOnRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
