# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.check_collections_replay_request import CheckCollectionsReplayRequest

class TestCheckCollectionsReplayRequest(unittest.TestCase):
    """CheckCollectionsReplayRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckCollectionsReplayRequest:
        """Test CheckCollectionsReplayRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckCollectionsReplayRequest`
        """
        model = CheckCollectionsReplayRequest()
        if include_optional:
            return CheckCollectionsReplayRequest(
                org_id = 'cntb',
                account_id = 'DE-123',
                creation_start_time = '2021-06-03T06:27:12Z',
                creation_end_time = '2021-06-03T10:27:12Z',
                rate = 10,
                check_collection_ids = [12345,23456]
            )
        else:
            return CheckCollectionsReplayRequest(
                org_id = 'cntb',
                account_id = 'DE-123',
        )
        """

    def testCheckCollectionsReplayRequest(self):
        """Test CheckCollectionsReplayRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
