# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.api.instance_actions_audits_api import InstanceActionsAuditsApi  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestInstanceActionsAuditsApi(unittest.TestCase):
    """InstanceActionsAuditsApi unit test stubs"""

    def setUp(self):
        self.api = InstanceActionsAuditsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_instances_actions_audits_list(self):
        """Test case for retrieve_instances_actions_audits_list

        List history about your actions (audit) triggered via the API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
