# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.api.roles_audits_api import RolesAuditsApi


class TestRolesAuditsApi(unittest.TestCase):
    """RolesAuditsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RolesAuditsApi()

    def tearDown(self) -> None:
        pass

    def test_retrieve_role_audits_list(self) -> None:
        """Test case for retrieve_role_audits_list

        List history about your roles (audit)
        """
        pass


if __name__ == '__main__':
    unittest.main()
