"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.links import Links
from pfruck_contabo.model.list_private_network_response_data import ListPrivateNetworkResponseData
from pfruck_contabo.model.pagination_meta import PaginationMeta
globals()['Links'] = Links
globals()['ListPrivateNetworkResponseData'] = ListPrivateNetworkResponseData
globals()['PaginationMeta'] = PaginationMeta
from pfruck_contabo.model.list_private_network_response import ListPrivateNetworkResponse


class TestListPrivateNetworkResponse(unittest.TestCase):
    """ListPrivateNetworkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListPrivateNetworkResponse(self):
        """Test ListPrivateNetworkResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListPrivateNetworkResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
