"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import pfruck_contabo
from pfruck_contabo.api.firewalls_audits_api import FirewallsAuditsApi  # noqa: E501


class TestFirewallsAuditsApi(unittest.TestCase):
    """FirewallsAuditsApi unit test stubs"""

    def setUp(self):
        self.api = FirewallsAuditsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_firewall_audits_list(self):
        """Test case for retrieve_firewall_audits_list

        List history about your Firewalls (audit)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
