"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.zerops_sign_in_response import ZeropsSignInResponse


class TestZeropsSignInResponse(unittest.TestCase):
    """ZeropsSignInResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZeropsSignInResponse(self):
        """Test ZeropsSignInResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ZeropsSignInResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
