"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.patch_instance_response_data import PatchInstanceResponseData
from pfruck_contabo.model.patch_instance_response_links import PatchInstanceResponseLinks
globals()['PatchInstanceResponseData'] = PatchInstanceResponseData
globals()['PatchInstanceResponseLinks'] = PatchInstanceResponseLinks
from pfruck_contabo.model.patch_instance_response import PatchInstanceResponse


class TestPatchInstanceResponse(unittest.TestCase):
    """PatchInstanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchInstanceResponse(self):
        """Test PatchInstanceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchInstanceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
