"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.find_firewall_response_links import FindFirewallResponseLinks
from pfruck_contabo.model.firewall_response import FirewallResponse
globals()['FindFirewallResponseLinks'] = FindFirewallResponseLinks
globals()['FirewallResponse'] = FirewallResponse
from pfruck_contabo.model.put_firewall_response import PutFirewallResponse


class TestPutFirewallResponse(unittest.TestCase):
    """PutFirewallResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutFirewallResponse(self):
        """Test PutFirewallResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PutFirewallResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
