# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.api.snapshots_audits_api import SnapshotsAuditsApi  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestSnapshotsAuditsApi(unittest.TestCase):
    """SnapshotsAuditsApi unit test stubs"""

    def setUp(self):
        self.api = SnapshotsAuditsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_snapshots_audits_list(self):
        """Test case for retrieve_snapshots_audits_list

        List history about your snapshots (audit) triggered via the API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
