# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.ext_remedies_get_response import ExtRemediesGetResponse

class TestExtRemediesGetResponse(unittest.TestCase):
    """ExtRemediesGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtRemediesGetResponse:
        """Test ExtRemediesGetResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtRemediesGetResponse`
        """
        model = ExtRemediesGetResponse()
        if include_optional:
            return ExtRemediesGetResponse(
                data = [
                    pfruck_contabo.models.ext_remedy_response.ExtRemedyResponse(
                        internal = False, 
                        status = 'failed', 
                        object_type = 'vserver', 
                        object_id = '4711', 
                        remedy_id = 12345, 
                        remedy_collection_id = 12345, 
                        remedy_template_id = 12345, 
                        name = 'Ping remedy', 
                        note = 'success_remedy_successful', 
                        internal_note = 'remedy_internal_error_internal', 
                        duration_ms = 4711, 
                        created_date = '1998-02-14T12:00:01.654Z', 
                        modified_date = '2024-12-14T12:00:01.654Z', 
                        tenant_id = 'DE', 
                        customer_id = '123456', )
                    ],
                links = pfruck_contabo.models.self_links.SelfLinks(
                    self = '', )
            )
        else:
            return ExtRemediesGetResponse(
                data = [
                    pfruck_contabo.models.ext_remedy_response.ExtRemedyResponse(
                        internal = False, 
                        status = 'failed', 
                        object_type = 'vserver', 
                        object_id = '4711', 
                        remedy_id = 12345, 
                        remedy_collection_id = 12345, 
                        remedy_template_id = 12345, 
                        name = 'Ping remedy', 
                        note = 'success_remedy_successful', 
                        internal_note = 'remedy_internal_error_internal', 
                        duration_ms = 4711, 
                        created_date = '1998-02-14T12:00:01.654Z', 
                        modified_date = '2024-12-14T12:00:01.654Z', 
                        tenant_id = 'DE', 
                        customer_id = '123456', )
                    ],
                links = pfruck_contabo.models.self_links.SelfLinks(
                    self = '', ),
        )
        """

    def testExtRemediesGetResponse(self):
        """Test ExtRemediesGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
