# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.changed_auth_code import ChangedAuthCode

class TestChangedAuthCode(unittest.TestCase):
    """ChangedAuthCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangedAuthCode:
        """Test ChangedAuthCode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangedAuthCode`
        """
        model = ChangedAuthCode()
        if include_optional:
            return ChangedAuthCode(
                changed = True,
                var_date = '2021-06-03T06:27:12Z'
            )
        else:
            return ChangedAuthCode(
        )
        """

    def testChangedAuthCode(self):
        """Test ChangedAuthCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
