"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.ip_v4 import IpV4
globals()['IpV4'] = IpV4
from pfruck_contabo.model.list_vip_response_data import ListVipResponseData


class TestListVipResponseData(unittest.TestCase):
    """ListVipResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListVipResponseData(self):
        """Test ListVipResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListVipResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
