# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.reinstall_instance_request import ReinstallInstanceRequest

class TestReinstallInstanceRequest(unittest.TestCase):
    """ReinstallInstanceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReinstallInstanceRequest:
        """Test ReinstallInstanceRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReinstallInstanceRequest`
        """
        model = ReinstallInstanceRequest()
        if include_optional:
            return ReinstallInstanceRequest(
                image_id = '3f184ab8-a600-4e7c-8c9b-3413e21a3752',
                ssh_keys = [123, 125],
                root_password = 1,
                user_data = '#cloud-config
user: admin
timezone: Europe/Berlin
chpasswd:
 expire: False',
                default_user = 'admin',
                application_id = '3f184ab8-a600-4e7c-8c9b-3413e21a3752'
            )
        else:
            return ReinstallInstanceRequest(
                image_id = '3f184ab8-a600-4e7c-8c9b-3413e21a3752',
        )
        """

    def testReinstallInstanceRequest(self):
        """Test ReinstallInstanceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
