"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import pfruck_contabo
from pfruck_contabo.api.secrets_api import SecretsApi  # noqa: E501


class TestSecretsApi(unittest.TestCase):
    """SecretsApi unit test stubs"""

    def setUp(self):
        self.api = SecretsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_secret(self):
        """Test case for create_secret

        Create a new secret  # noqa: E501
        """
        pass

    def test_delete_secret(self):
        """Test case for delete_secret

        Delete existing secret by id  # noqa: E501
        """
        pass

    def test_retrieve_secret(self):
        """Test case for retrieve_secret

        Get specific secret by id  # noqa: E501
        """
        pass

    def test_retrieve_secret_list(self):
        """Test case for retrieve_secret_list

        List secrets  # noqa: E501
        """
        pass

    def test_update_secret(self):
        """Test case for update_secret

        Update specific secret by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
