# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.api.check_collections_api import CheckCollectionsApi


class TestCheckCollectionsApi(unittest.TestCase):
    """CheckCollectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CheckCollectionsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_ext_check_collection(self) -> None:
        """Test case for cancel_ext_check_collection

        Cancel check collection
        """
        pass

    def test_get_ext_check_collection(self) -> None:
        """Test case for get_ext_check_collection

        Get check collection
        """
        pass

    def test_list_ext_check_collections(self) -> None:
        """Test case for list_ext_check_collections

        List check collections
        """
        pass

    def test_start_ext_check_collection(self) -> None:
        """Test case for start_ext_check_collection

        Start check collection
        """
        pass


if __name__ == '__main__':
    unittest.main()
