# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.find_secret_response import FindSecretResponse

class TestFindSecretResponse(unittest.TestCase):
    """FindSecretResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindSecretResponse:
        """Test FindSecretResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindSecretResponse`
        """
        model = FindSecretResponse()
        if include_optional:
            return FindSecretResponse(
                data = [
                    pfruck_contabo.models.secret_response.SecretResponse(
                        tenant_id = 'DE', 
                        customer_id = '54321', 
                        secret_id = 12345, 
                        name = 'Password Secret', 
                        type = 'password', 
                        value = 'password', 
                        created_at = '2021-06-03T06:27:12Z', 
                        updated_at = '2021-06-03T06:27:12Z', )
                    ],
                links = pfruck_contabo.models.self_links.SelfLinks(
                    self = '', )
            )
        else:
            return FindSecretResponse(
                data = [
                    pfruck_contabo.models.secret_response.SecretResponse(
                        tenant_id = 'DE', 
                        customer_id = '54321', 
                        secret_id = 12345, 
                        name = 'Password Secret', 
                        type = 'password', 
                        value = 'password', 
                        created_at = '2021-06-03T06:27:12Z', 
                        updated_at = '2021-06-03T06:27:12Z', )
                    ],
                links = pfruck_contabo.models.self_links.SelfLinks(
                    self = '', ),
        )
        """

    def testFindSecretResponse(self):
        """Test FindSecretResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
