"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.list_snapshot_response_links import ListSnapshotResponseLinks
from pfruck_contabo.model.list_user_response_pagination import ListUserResponsePagination
from pfruck_contabo.model.snapshot_response import SnapshotResponse
globals()['ListSnapshotResponseLinks'] = ListSnapshotResponseLinks
globals()['ListUserResponsePagination'] = ListUserResponsePagination
globals()['SnapshotResponse'] = SnapshotResponse
from pfruck_contabo.model.list_snapshot_response import ListSnapshotResponse


class TestListSnapshotResponse(unittest.TestCase):
    """ListSnapshotResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListSnapshotResponse(self):
        """Test ListSnapshotResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListSnapshotResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
