# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.models.all_of_list_snapshots_audit_response_pagination import AllOfListSnapshotsAuditResponsePagination  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestAllOfListSnapshotsAuditResponsePagination(unittest.TestCase):
    """AllOfListSnapshotsAuditResponsePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfListSnapshotsAuditResponsePagination(self):
        """Test AllOfListSnapshotsAuditResponsePagination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pfruck_contabo.models.all_of_list_snapshots_audit_response_pagination.AllOfListSnapshotsAuditResponsePagination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
