# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.create_firewall_request import CreateFirewallRequest

class TestCreateFirewallRequest(unittest.TestCase):
    """CreateFirewallRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFirewallRequest:
        """Test CreateFirewallRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFirewallRequest`
        """
        model = CreateFirewallRequest()
        if include_optional:
            return CreateFirewallRequest(
                name = 'My Firewall',
                description = 'Allowing incoming HTTP traffic.',
                status = 'active',
                rules = pfruck_contabo.models.rules_request.RulesRequest(
                    inbound = [
                        pfruck_contabo.models.firewall_rule_request.FirewallRuleRequest(
                            protocol = 'tcp', 
                            dest_ports = ["80", "80-90"], 
                            src_cidr = null, 
                            action = 'accept', 
                            status = 'active', 
                            display_name = 'Allow HTTP Traffic', )
                        ], )
            )
        else:
            return CreateFirewallRequest(
                name = 'My Firewall',
                status = 'active',
        )
        """

    def testCreateFirewallRequest(self):
        """Test CreateFirewallRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
