# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.extra_storage_request import ExtraStorageRequest

class TestExtraStorageRequest(unittest.TestCase):
    """ExtraStorageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtraStorageRequest:
        """Test ExtraStorageRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtraStorageRequest`
        """
        model = ExtraStorageRequest()
        if include_optional:
            return ExtraStorageRequest(
                ssd = [
                    ''
                    ],
                nvme = [
                    ''
                    ]
            )
        else:
            return ExtraStorageRequest(
        )
        """

    def testExtraStorageRequest(self):
        """Test ExtraStorageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
