# coding: utf-8

"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pfruck_contabo.models.remedies_create_request import RemediesCreateRequest

class TestRemediesCreateRequest(unittest.TestCase):
    """RemediesCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemediesCreateRequest:
        """Test RemediesCreateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemediesCreateRequest`
        """
        model = RemediesCreateRequest()
        if include_optional:
            return RemediesCreateRequest(
                object_type = 'vserver',
                object_id = '4711',
                remedy_template_id = 12345,
                remedy_collection_id = 12345,
                org_id = 'cntb',
                account_id = 'DE-123'
            )
        else:
            return RemediesCreateRequest(
                object_type = 'vserver',
                object_id = '4711',
                remedy_template_id = 12345,
                org_id = 'cntb',
                account_id = 'DE-123',
        )
        """

    def testRemediesCreateRequest(self):
        """Test RemediesCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
