# coding: utf-8

"""
    Contabo API


    OpenAPI spec version: 1.0.0
    Contact: support@contabo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pfruck_contabo
from pfruck_contabo.models.assignment_audit_response import AssignmentAuditResponse  # noqa: E501
from pfruck_contabo.rest import ApiException


class TestAssignmentAuditResponse(unittest.TestCase):
    """AssignmentAuditResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssignmentAuditResponse(self):
        """Test AssignmentAuditResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pfruck_contabo.models.assignment_audit_response.AssignmentAuditResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
