"""
    Contabo API


    The version of the OpenAPI document: 1.0.0
    Contact: support@contabo.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pfruck_contabo
from pfruck_contabo.model.self_links import SelfLinks
globals()['SelfLinks'] = SelfLinks
from pfruck_contabo.model.update_secret_response_links import UpdateSecretResponseLinks


class TestUpdateSecretResponseLinks(unittest.TestCase):
    """UpdateSecretResponseLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSecretResponseLinks(self):
        """Test UpdateSecretResponseLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateSecretResponseLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
