name: Auto update

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 18 * * *'  # every day at 6 PM

jobs:
  gh-update:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: write
      deployments: none
      issues: none
      packages: none
      pull-requests: write
      repository-projects: none
      security-events: none
      statuses: none
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          ref: main

      - name: "Rebuild project"
        run: make

      - name: "Commit and publish the changes"
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "nightly API update"
          committer: "Philipp Fruck <p-fruck@users.noreply.github.com>"
          author: "Philipp Fruck <p-fruck@users.noreply.github.com>"
          branch: nightly
          delete-branch: true
          base: main
          title: "API-Update: <nightly>"
          body: |
            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.

            Make sure to review the changes before approving and merging. Provide a small summary of the given changes.
          labels: "auto-update"
          assignees: p-fruck
          reviewers: p-fruck
          draft: true
